(module
  (import "env" "unused_mem" (memory $imported_mem 1))
  (import "env" "unused_tab" (table $imported_tab 1 funcref))
  (import "env" "unused_tag" (tag $imported_tag (param i32)))
  (memory $used_mem 1)
  (memory $unused_mem 1)
  (memory $_ignored_mem 1)
  (table $used_tab 1 funcref)
  (table $unused_tab 1 funcref)
  (tag $used_tag (param i32))
  (tag $unused_tag (param i32))
  (data $used_data "ab")
  (data $unused_data "cd")
  (data (memory $used_mem) (i32.const 0) "active")
  (elem $used_elem funcref (ref.func $f))
  (elem $unused_elem funcref)
  (elem (table $used_tab) (i32.const 0) funcref (ref.func $f))
  (func $f (export "f")
    (memory.init $used_mem $used_data (i32.const 0) (i32.const 0) (i32.const 1))
    (table.init $used_tab $used_elem (i32.const 0) (i32.const 0) (i32.const 1))
    (throw $used_tag (i32.const 0))))
