(module
  (type $s (sub (struct (field i32))))
  (func $f (result i32) (i32.const 0))
  (func $write_once (result funcref)
    (local $x funcref)
    (local.set $x (ref.func $f))
    (local.get $x))
  (func $reassigned (result funcref)
    (local $y funcref)
    (local.set $y (ref.func $f))
    (local.set $y (ref.null func))
    (local.get $y))
  (func $write_once_struct (result eqref)
    (local $z eqref)
    (local.set $z (struct.new $s (i32.const 7)))
    (local.get $z)))
