version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "/npm"
      - "/tree-sitter-wax"
      - "/editors/vscode"
      - "/docs/tools/wax-highlight"
    schedule:
      interval: "weekly"
    groups:
      npm:
        patterns:
          - "*"
