#!/usr/bin/env bash
#
# wax-corpus.sh [smith-count] [smith-bytes]
#
# Build a corpus of Wax *source* files to seed the mutation fuzzer (mutate-wax.sh)
# and feed the oracle directly (run.sh fuzz/corpus-wax). Two sources, both
# decompiled to .wax with wax itself (so every seed is valid, type-correct Wax —
# wax's own output):
#   1. the known-valid wasm corpus (fuzz/corpus/valid, from build-corpus.sh) —
#      small, curated spec-suite modules covering specific constructs cleanly;
#   2. `smith-count` (default 1000) modules generated by `wasm-tools smith` with
#      `smith-bytes` (default 8192) seed bytes — far larger and more intertwined
#      than the spec modules (tens to hundreds of lines vs a handful), so the AST
#      mutator explores deep, realistic code rather than only tiny snippets.
#
# Output goes under fuzz/corpus-wax/valid/ (override with OUT; spec source with
# SRC) so run.sh treats each file as EXPECT=valid: a wax rejection of wax's own
# output is then a FALSE_REJECT (a printer/parser or typer disagreement). Modules
# wax cannot decompile (an unsupported proposal) are skipped.
#
# Parallel across cores (override with JOBS).

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

SMITH_COUNT="${1:-1000}"
SMITH_BYTES="${2:-8192}"
SRC="${SRC:-$ROOT/fuzz/corpus/valid}"
OUT="${OUT:-$ROOT/fuzz/corpus-wax}"
JOBS="${JOBS:-$(nproc 2>/dev/null || echo 4)}"
rm -rf "$OUT"; mkdir -p "$OUT/valid"
export WAX WASM_TOOLS TIMEOUT OUT SMITH_BYTES SMITH_FLAGS

# Worker: decompile one existing wasm module to wax (progress: . kept, s skipped).
decompile_one() {
  local f="$1" out
  out="$OUT/valid/$(basename "${f%.*}").wax"
  if timeout "$TIMEOUT" "$WAX" -i wasm -f wax "$f" -o "$out" 2>/dev/null; then
    printf '.' >&2
  else
    rm -f "$out"; printf 's' >&2
  fi
}
export -f decompile_one

# Worker: generate smith module #i from fresh random bytes and decompile it to
# wax (s = smith failed or wax could not decompile it).
smith_one() {
  local i="$1" seed mod
  seed="$(mktemp)"; mod="$(mktemp --suffix=.wasm)"
  head -c "$SMITH_BYTES" /dev/urandom >"$seed"
  if "$WASM_TOOLS" smith $SMITH_FLAGS "$seed" -o "$mod" 2>/dev/null \
    && timeout "$TIMEOUT" "$WAX" -i wasm -f wax "$mod" -o "$OUT/valid/smith-$i.wax" 2>/dev/null; then
    printf '.' >&2
  else
    rm -f "$OUT/valid/smith-$i.wax"; printf 's' >&2
  fi
  rm -f "$seed" "$mod"
}
export -f smith_one

if [ -d "$SRC" ]; then
  spec=$(find "$SRC" -name '*.wasm' | wc -l)
  echo "decompiling $spec spec-corpus modules across $JOBS jobs..." >&2
  find "$SRC" -name '*.wasm' -print0 \
    | xargs -0 -P "$JOBS" -I{} bash -c 'decompile_one "$@"' _ {}
  echo >&2
else
  echo "no wasm corpus at $SRC (run fuzz/build-corpus.sh) — using smith seeds only" >&2
fi

if [ "$SMITH_COUNT" -gt 0 ]; then
  echo "generating + decompiling $SMITH_COUNT smith modules ($SMITH_BYTES bytes) across $JOBS jobs..." >&2
  seq 1 "$SMITH_COUNT" | xargs -P "$JOBS" -I{} bash -c 'smith_one "$@"' _ {}
  echo >&2
fi

n=$(find "$OUT/valid" -name '*.wax' | wc -l)
echo "wax corpus: $n seeds -> $OUT/valid"
