#!/usr/bin/env bash
#
# wax-corpus.sh [smith-count] [smith-bytes]
#
# Build a corpus of Wax *source* files to seed the mutation fuzzer (mutate-wax.sh)
# and feed the oracle directly (run.sh fuzz/corpus-wax). Three sources:
#
#   1. the known-valid wasm corpus (fuzz/corpus/valid, from build-corpus.sh) —
#      small, curated spec-suite modules covering specific constructs cleanly;
#   2. `smith-count` (default 1000) modules generated by `wasm-tools smith` with
#      `smith-bytes` (default 8192) seed bytes — far larger and more intertwined
#      than the spec modules (tens to hundreds of lines vs a handful), so the AST
#      mutator explores deep, realistic code rather than only tiny snippets.
#
#   Sources 1 and 2 are both decompiled to .wax with wax itself, so every seed is
#   valid, type-correct Wax — but it is *wax's own output*, a fixed point of the
#   wasm->wax simplify pass. Such a seed can never exhibit a dropped-annotation
#   round-trip bug (the annotation was already dropped when it was produced). So:
#
#   3. AUTHORIAL (hand-written) Wax (skip with AUTHORIAL=0) — carries the explicit
#      type annotations decompiled output lacks. Three sub-sources, each file kept
#      only if `wax check` accepts it as-is (the corpus contract is EXPECT=valid;
#      many cram fixtures are deliberate negative tests, and files needing `-D`
#      defines or `-X` features exit non-zero under a plain check and are skipped):
#        (a) every *.wax fixture under test/cram-tests/*/;
#        (b) the ```wax code blocks in docs/src/examples.md;
#        (c) infer.wax at the repo root, if it type-checks.
#      These are named authorial-* so triage can tell them from decompiled seeds,
#      and they are what gives annot-fuzz.sh / oracle 6 real hand-written Wax to
#      round-trip.
#
# Output goes under fuzz/corpus-wax/valid/ (override with OUT; spec source with
# SRC) so run.sh treats each file as EXPECT=valid: a wax rejection of wax's own
# output is then a FALSE_REJECT (a printer/parser or typer disagreement). Modules
# wax cannot decompile (an unsupported proposal) are skipped.
#
# Parallel across cores (override with JOBS).

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

SMITH_COUNT="${1:-1000}"
SMITH_BYTES="${2:-8192}"
SRC="${SRC:-$ROOT/fuzz/corpus/valid}"
OUT="${OUT:-$ROOT/fuzz/corpus-wax}"
# Decompilation is latency-bound (a short-lived wax fork per module), so
# oversubscribe to fill the idle cores (like smith.sh) — ~4x the core count.
JOBS="${JOBS:-$(( $(nproc 2>/dev/null || echo 4) * 4 ))}"
rm -rf "$OUT"; mkdir -p "$OUT/valid"
export WAX WASM_TOOLS TIMEOUT OUT SMITH_BYTES SMITH_FLAGS

# Worker: decompile one existing wasm module to wax (progress: . kept, s skipped).
decompile_one() {
  local f="$1" out
  out="$OUT/valid/$(basename "${f%.*}").wax"
  if timeout "$TIMEOUT" "$WAX" -i wasm -f wax "$f" -o "$out" 2>/dev/null; then
    printf '.' >&2
  else
    rm -f "$out"; printf 's' >&2
  fi
}
export -f decompile_one

# Worker: generate smith module #i from fresh random bytes and decompile it to
# wax (s = smith failed or wax could not decompile it).
smith_one() {
  local i="$1" seed mod
  seed="$(mktemp)"; mod="$(mktemp --suffix=.wasm)"
  rand_bytes "$SEED-$i" "$SMITH_BYTES" >"$seed"
  if "$WASM_TOOLS" smith $SMITH_FLAGS "$seed" -o "$mod" 2>/dev/null \
    && timeout "$TIMEOUT" "$WAX" -i wasm -f wax "$mod" -o "$OUT/valid/smith-$i.wax" 2>/dev/null; then
    printf '.' >&2
  else
    rm -f "$OUT/valid/smith-$i.wax"; printf 's' >&2
  fi
  rm -f "$seed" "$mod"
}
export -f smith_one

if [ -d "$SRC" ]; then
  spec=$(find "$SRC" -name '*.wasm' | wc -l)
  echo "decompiling $spec spec-corpus modules across $JOBS jobs..." >&2
  find "$SRC" -name '*.wasm' -print0 \
    | xargs -0 -P "$JOBS" -I{} bash -c 'decompile_one "$@"' _ {}
  echo >&2
else
  echo "no wasm corpus at $SRC (run fuzz/build-corpus.sh) — using smith seeds only" >&2
fi

if [ "$SMITH_COUNT" -gt 0 ]; then
  echo "generating + decompiling $SMITH_COUNT smith modules ($SMITH_BYTES bytes) across $JOBS jobs..." >&2
  seq 1 "$SMITH_COUNT" | xargs -P "$JOBS" -I{} bash -c 'smith_one "$@"' _ {}
  echo >&2
fi

# ---- 3. Authorial (hand-written) Wax seeds (see the header). ----
# Copied verbatim (not decompiled) so they retain their explicit annotations;
# only kept when a plain `wax check` accepts them (EXPECT=valid corpus contract).
if [ "${AUTHORIAL:-1}" != 0 ]; then
  echo "collecting authorial wax seeds (cram fixtures, doc examples, infer.wax)..." >&2
  na=0
  # (a) cram-test .wax fixtures. Name from the path (dir-qualified) so basenames
  # that repeat across .t directories (try.wax, errors.wax, ...) stay distinct.
  while IFS= read -r f; do
    rel="${f#"$ROOT"/test/cram-tests/}"
    name="authorial-$(printf '%s' "$rel" | sed 's/\.wax$//; s#[/.]#-#g')"
    if "$WAX" check "$f" >/dev/null 2>&1; then
      cp "$f" "$OUT/valid/$name.wax"; na=$((na + 1))
    fi
  done < <(find "$ROOT/test/cram-tests" -name '*.wax' | sort)
  # (b) ```wax code blocks in docs/src/examples.md (same extraction as the
  # docs-examples cram test).
  if [ -f "$ROOT/docs/src/examples.md" ]; then
    exd="$(mktemp -d)"
    awk -v d="$exd" '
      /^```wax$/ { f = 1; n++; out = sprintf("%s/example-%02d.wax", d, n); next }
      /^```$/    { f = 0; next }
      f          { print > out }' "$ROOT/docs/src/examples.md"
    for f in "$exd"/example-*.wax; do
      [ -e "$f" ] || continue
      if "$WAX" check "$f" >/dev/null 2>&1; then
        cp "$f" "$OUT/valid/authorial-$(basename "$f")"; na=$((na + 1))
      fi
    done
    rm -rf "$exd"
  fi
  # (c) infer.wax at the repo root.
  if [ -f "$ROOT/infer.wax" ] && "$WAX" check "$ROOT/infer.wax" >/dev/null 2>&1; then
    cp "$ROOT/infer.wax" "$OUT/valid/authorial-infer.wax"; na=$((na + 1))
  fi
  echo "authorial seeds included: $na" >&2
fi

n=$(find "$OUT/valid" -name '*.wax' | wc -l)
echo "wax corpus: $n seeds -> $OUT/valid"
