(* Generates src/lib-utils/xid.ml: sorted (lo, hi) codepoint ranges for the
   Unicode XID_Start and XID_Continue properties, plus binary-search predicates.
   Committed and read at runtime, so a normal build never needs uucp. Regenerate
   (from a switch that has uucp) with:
     dune build @src/lib-utils/regenerate-xid *)

let ranges pred =
  let out = ref [] in
  let start = ref (-1) and prev = ref (-2) in
  let flush () = if !start >= 0 then out := (!start, !prev) :: !out in
  for c = 0 to 0x10FFFF do
    (* Skip the surrogate range: [Uchar.of_int] rejects it. *)
    if c < 0xD800 || c > 0xDFFF then
      if pred (Uchar.of_int c) then (
        if !start < 0 then start := c
        else if c <> !prev + 1 then (
          flush ();
          start := c);
        prev := c)
  done;
  flush ();
  List.rev !out

let emit name pred =
  Printf.printf "let %s =\n  [|" name;
  List.iter (fun (a, b) -> Printf.printf "(0x%X, 0x%X); " a b) (ranges pred);
  Printf.printf "|]\n\n"

let () =
  Printf.printf
    "(* Auto-generated by scripts/build_xid_table; do not edit. Regenerate with\n\
    \   [dune build @src/lib-utils/regenerate-xid]. *)\n\n";
  emit "start_ranges" Uucp.Id.is_xid_start;
  emit "continue_ranges" Uucp.Id.is_xid_continue;
  print_string
    "let mem ranges c =\n\
    \  let rec go lo hi =\n\
    \    if lo > hi then false\n\
    \    else\n\
    \      let m = (lo + hi) / 2 in\n\
    \      let a, b = ranges.(m) in\n\
    \      if c < a then go lo (m - 1) else if c > b then go (m + 1) hi else \
     true\n\
    \  in\n\
    \  go 0 (Array.length ranges - 1)\n\n\
     let is_xid_start c = mem start_ranges c\n\
     let is_xid_continue c = mem continue_ranges c\n"
