(* 
   Analysis and Error Message Generation for Menhir .messages files.
   
   This tool provides functionality to:
   1. Parse .messages files.
   2. Analyze grammar to understand symbol expansions.
   3. Generate user-friendly error messages using heuristics.
*)

module StringSet = Set.Make (String)
module StringMap = Map.Make (String)
module StatusMap = Map.Make (String)

type status = Direct | Lookahead | Both

(* --- Grammar Analysis Utilities --- *)

(* Build a grammar (LHS -> RHS list map) from all LR items in the file *)
let build_grammar entries =
  List.fold_left
    (fun acc entry ->
      List.fold_left
        (fun acc item ->
          let lhs = item.Parse_messages.lhs in
          let rhs =
            item.Parse_messages.rhs_before @ item.Parse_messages.rhs_after
          in
          let existing = try StringMap.find lhs acc with Not_found -> [] in
          if List.mem rhs existing then acc
          else StringMap.add lhs (rhs :: existing) acc)
        acc entry.Parse_messages.data.lr1_items)
    StringMap.empty entries

(* Strips constructors like option(), list(), etc. to get the inner symbol.
   Table-driven over [(prefix, has_separator)]: a plain wrapper yields its sole
   argument; a separated_* wrapper names the instantiation with the separator
   token first (e.g. [separated_nonempty_list_trailing(COMMA,on_clause)]), so its
   element is the second comma-field. The trailing-comma variants were once
   missed exactly because they were hand-copied and forgotten, hence the table. *)
let strip_constructor s =
  let open String in
  let len = length s in
  let table =
    [
      ("loption(", false);
      ("option(", false);
      ("boption(", false);
      ("list(", false);
      ("semi_list(", false);
      ("nonempty_list(", false);
      ("separated_list(", true);
      ("separated_nonempty_list(", true);
      ("separated_list_trailing(", true);
      ("separated_nonempty_list_trailing(", true);
    ]
  in
  let apply (prefix, has_separator) =
    if starts_with ~prefix s && ends_with ~suffix:")" s then
      let plen = length prefix in
      let content = sub s plen (len - plen - 1) in
      if has_separator then
        match split_on_char ',' content with
        | _ :: x :: _ -> Some (trim x)
        | _ -> Some s
      else Some content
    else None
  in
  match
    List.fold_left
      (fun acc entry -> match acc with Some _ -> acc | None -> apply entry)
      None table
  with
  | Some r -> r
  | None -> s

(* Check if a symbol involves an anonymous symbol generated by Menhir *)
let involves_anonymous s =
  let pattern = "__anonymous" in
  let plen = String.length pattern in
  let slen = String.length s in
  let rec check i =
    if i + plen > slen then false
    else if String.sub s i plen = pattern then true
    else check (i + 1)
  in
  check 0

(* Check if a symbol is nullable (heuristic based on name) *)
let is_nullable_symbol s =
  let prefixes = [ "option("; "boption("; "loption("; "list("; "semi_list(" ] in
  List.exists
    (fun prefix ->
      String.length s >= String.length prefix
      && String.sub s 0 (String.length prefix) = prefix)
    prefixes

(* Recursively expand non-terminals to find the set of first terminals/symbols they can produce *)
let rec expand_symbol grammar visited s =
  if StringSet.mem s visited then StringSet.empty (* Cycle detection *)
  else
    let visited' = StringSet.add s visited in

    (* Attempt 1: Expand via grammar if applicable (for anonymous symbols) *)
    let try_grammar () =
      if involves_anonymous s then
        match StringMap.find_opt s grammar with
        | Some productions ->
            let result =
              List.fold_left
                (fun acc rhs ->
                  match rhs with
                  | [] -> acc (* Empty production *)
                  | first :: _ ->
                      let firsts = expand_symbol grammar visited' first in
                      StringSet.union acc firsts)
                StringSet.empty productions
            in
            Some result
        | None -> None
      else None
    in

    match try_grammar () with
    | Some res -> res
    | None ->
        (* Attempt 2: Unwrap constructors *)
        let s_unwrapped = strip_constructor s in
        if s_unwrapped <> s then
          (* Recurse on unwrapped *)
          expand_symbol grammar visited' s_unwrapped
        else
          (* Terminal or opaque non-terminal found *)
          StringSet.singleton s

(* Helper for StatusMap *)
let add_status s status map =
  let new_status =
    match StatusMap.find_opt s map with
    | None -> status
    | Some old -> if old = status then old else Both
  in
  StatusMap.add s new_status map

let union_status map1 map2 =
  StatusMap.fold (fun s status acc -> add_status s status acc) map2 map1

(* 
   Collect all possible next symbols (continuations) given the RHS after the dot.
   Handles nullability to look past nullable symbols.
*)
let rec collect_continuations grammar visited rhs_after lookaheads =
  match rhs_after with
  | [] ->
      List.fold_left
        (fun acc s -> add_status s Lookahead acc)
        StatusMap.empty lookaheads
  | symbol :: rest ->
      (* Expand the symbol *)
      let expanded = expand_symbol grammar visited symbol in

      let base_map =
        StringSet.fold
          (fun s acc -> add_status s Direct acc)
          expanded StatusMap.empty
      in
      let acc = base_map in

      if is_nullable_symbol symbol then
        let rest_map = collect_continuations grammar visited rest lookaheads in
        union_status acc rest_map
      else acc

(* --- Depth Calculation --- *)

(* The opening delimiter each closer terminates, keyed by the closer's own
   readable spelling: a ')' closes a '(', etc. A terminal is an opener for that
   closer when its token alias begins with this character — so the opener table
   is derived from the grammar's [%token NAME "alias"] declarations rather than
   hand-maintained (the hand-list went stale, missing e.g. the [(@if] / [(on]
   openers). *)
let opener_char_of_closer = function
  | "RBRACE" -> Some '{'
  | "RBRACKET" -> Some '['
  | "RPAREN" -> Some '('
  | _ -> None

let opens_with terminals c token =
  match Hashtbl.find_opt terminals token with
  | Some a -> String.length a > 0 && a.[0] = c
  | None -> false

(*
   Find depth of the matching opener for a given closer.
   Depth is defined as the 1-based index from the top of the stack (right end of the sentence).
   Every token counts as depth 1.
*)
let find_matching_depth terminals sentence closer =
  let tokens =
    String.split_on_char ' ' sentence
    |> List.map String.trim
    |> List.filter (fun s -> s <> "")
  in
  let reversed = List.rev tokens in

  match opener_char_of_closer closer with
  | None -> None
  | Some opener_c ->
      let rec scan depth balance items =
        match items with
        | [] -> None (* Not found *)
        | token :: rest ->
            let current_depth = depth + 1 in
            if token = closer then scan current_depth (balance + 1) rest
            else if opens_with terminals opener_c token then
              if balance > 0 then scan current_depth (balance - 1) rest
              else Some current_depth
            else scan current_depth balance rest
      in
      scan 0 0 reversed

(* --- Terminal Alias Loading --- *)

let load_terminals filename =
  let mapping = Hashtbl.create 100 in
  let chan = open_in filename in
  let re_token =
    Str.regexp
      "%token[ \t]+\\(<[^>]+>\\)?[ \t]*\\([A-Z_0-9]+\\)[ \t]*\\(\"[^\"]+\"\\)?"
  in
  try
    while true do
      let line = input_line chan in
      if Str.string_match re_token line 0 then
        let name = Str.matched_group 2 line in
        match try Some (Str.matched_group 3 line) with Not_found -> None with
        | Some s ->
            let alias = String.sub s 1 (String.length s - 2) in
            Hashtbl.add mapping name alias
        | None -> ()
    done;
    assert false
  with End_of_file ->
    close_in chan;
    mapping

(* --- Message Generation --- *)

let format_human_list items =
  match List.rev items with
  | [] -> ""
  | [ x ] -> x
  | last :: rest -> String.concat ", " (List.rev rest) ^ ", or " ^ last

(* Fixed readable names for symbols whose auto-derived rendering would be
   internal jargon or grammatically wrong; [None] falls through to the
   derivation in [get_readable_name]. *)
let special_name = function
  | "IDENT" -> Some "an identifier"
  | "INT" -> Some "an integer"
  | "FLOAT" -> Some "a float"
  | "STRING" -> Some "a string"
  | "CHAR" -> Some "a character"
  | "EOF" -> Some "end of file"
  | "u8" -> Some "an 8-bit unsigned integer"
  | "u32" -> Some "a 32-bit unsigned integer"
  | "u64" -> Some "a 64-bit unsigned integer"
  | "i8" -> Some "an 8-bit signed integer"
  | "i16" -> Some "a 16-bit signed integer"
  | "i32" -> Some "a 32-bit signed integer"
  | "i64" -> Some "a 64-bit signed integer"
  | "f32" -> Some "a 32-bit float"
  | "f64" -> Some "a 64-bit float"
  | "LPAREN_IMPORT" -> Some "an inline import"
  | "NAT" -> Some "an integer"
  | "MEM_OFFSET" -> Some "a memory offset"
  | "MEM_ALIGN" -> Some "a memory alignment"
  (* Readable names for grammar nonterminals whose auto-derived form is
     internal jargon ("a blockinstr") or grammatically wrong ("a mem limits",
     where the [is_plural] heuristic below misfires). A plural alias carries no
     article, so the "Assuming that the … is/are complete" template picks
     "are"; a singular one keeps its article. *)
  | "blockinstr" | "braced_block" -> Some "a block"
  | "import_kind_decl" -> Some "an import declaration"
  | "on_clauses" -> Some "an on-clause list"
  | "mem_limits" -> Some "memory limits"
  | "mem_pagesize" | "pagesize_clause" -> Some "a page-size clause"
  | "condition_relop" -> Some "a comparison operator"
  | "branch_expr" -> Some "a branch expression"
  | "legacy_catch" -> Some "a catch clause"
  | "legacy_catch_all" -> Some "a catch-all clause"
  (* WAT (lib-wasm) nonterminals whose derived name is an abbreviation or reads
     oddly. *)
  | "result_pat" -> Some "a result pattern"
  | "float_or_nan" -> Some "a float or NaN"
  (* Head noun is "list", not the plural tail: keep the article so the
     "… is complete" template agrees ("the list of indices is", not "are"). *)
  | "list_of_indices" -> Some "a list of indices"
  | _ -> None

(* Collapse the many wax infix-operator continuations into a single readable
   class *before* the <=5 cap, so a state whose FOLLOW is "a closer or any
   operator" (e.g. the [expression] FOLLOW) reads "Expecting ')', or an
   operator." instead of overflowing to the generic fallback. Keyed by wax token
   name; the WAT grammar has none of these tokens, so it is unaffected. The
   compound-assignment variants ([+=] …) are operators too and join the class. *)
let operator_tokens =
  [
    "PLUS";
    "MINUS";
    "STAR";
    "SLASH";
    "SLASHS";
    "SLASHU";
    "PERCENTS";
    "PERCENTU";
    "AMPERSAND";
    "PIPE";
    "CARET";
    "SHL";
    "SHRS";
    "SHRU";
    "PLUSEQUAL";
    "MINUSEQUAL";
    "STAREQUAL";
    "SLASHEQUAL";
    "SLASHSEQUAL";
    "SLASHUEQUAL";
    "PERCENTSEQUAL";
    "PERCENTUEQUAL";
    "AMPERSANDEQUAL";
    "PIPEEQUAL";
    "CARETEQUAL";
    "SHLEQUAL";
    "SHRSEQUAL";
    "SHRUEQUAL";
  ]

let comparison_tokens =
  [
    "EQUALEQUAL";
    "BANGEQUAL";
    "LT";
    "LTS";
    "LTU";
    "LE";
    "LES";
    "LEU";
    "GT";
    "GTS";
    "GTU";
    "GE";
    "GES";
    "GEU";
  ]

let classify_symbol s =
  if List.mem s operator_tokens then Some "an operator"
  else if List.mem s comparison_tokens then Some "a comparison operator"
  else None

let get_readable_name terminals s =
  try Printf.sprintf "'%s'" (Hashtbl.find terminals s)
  with Not_found -> (
    match special_name s with
    | Some name -> name
    | None ->
        if String.lowercase_ascii s = s then
          (* Non-terminals: "some_name" -> "a/an some name" *)
          let parts = String.split_on_char '_' s in
          let parts = List.filter (fun p -> p <> "") parts in
          if parts = [] then s
          else
            let name = String.concat " " parts in
            match parts with
            | p :: _ ->
                let c = String.get p 0 in
                (* Drop the article for a plural noun phrase ("folded
                   instructions", not "a folded instructions"). Plurality is
                   decided by the LAST word — "descriptor clauses" is plural,
                   "expression list" is not — so the article agrees with the
                   head noun. *)
                let last = List.nth parts (List.length parts - 1) in
                let is_plural =
                  String.length last > 1
                  && String.sub last (String.length last - 1) 1 = "s"
                  && not
                       (List.mem last
                          [ "as"; "is"; "this"; "plus"; "minus"; "address" ])
                in
                if is_plural then name
                else if List.mem c [ 'a'; 'e'; 'i'; 'o'; 'u' ] then "an " ^ name
                else "a " ^ name
            | _ -> name
        else
          (* Keywords/Other Terminals: "TOKEN" -> "'token'" *)
          "'" ^ String.lowercase_ascii s ^ "'")

(* --- Self-Lints and Statistics --- *)

type message_stat = {
  expecting : bool;  (** A real "Expecting …" list was emitted. *)
  assuming : bool;  (** The spurious-reduction template was used. *)
  empty_expected : bool;
      (** Generic fallback: no symbols left after filtering. *)
  overflow_expected : bool;  (** Generic fallback: more than 5 symbols. *)
  hinted : bool;  (** A delimiter depth hint was emitted. *)
  missed_hints : string list;
      (** Closers that are valid in this state and have an opener-looking token
          on the known stack suffix, yet [find_matching_depth] found no match —
          the symptom of a stale opener table in [find_matching_depth]. *)
  jargon : StringSet.t;
      (** Terminals emitted in a message through the last-resort
          quoted-lowercase rendering whose name contains '_' (e.g.
          'string_annot') — jargon, not source syntax; needs an alias in the
          grammar or a [special_name] entry. *)
}

(* Would [token] plausibly open the construct [closer] terminates? Broader than
   the exact table in [find_matching_depth] on purpose: this is the lint's net
   for openers that table forgot. *)
let opener_like terminals closer token =
  let alias_starts c =
    match Hashtbl.find_opt terminals token with
    | Some a -> String.length a > 0 && a.[0] = c
    | None -> false
  in
  match closer with
  | "RBRACE" -> token = "LBRACE" || alias_starts '{'
  | "RBRACKET" -> token = "LBRACKET" || alias_starts '['
  | "RPAREN" ->
      String.starts_with ~prefix:"LPAREN" token
      || String.ends_with ~suffix:"_ANNOT" token
      || alias_starts '('
  | _ -> false

(* Does the known stack suffix contain an opener-like token with no matching
   closer? Same balance scan as [find_matching_depth], but with the broad
   [opener_like] net as the opener test — so the lint reports a genuinely
   unmatched opener [find_matching_depth]'s (narrower) table missed, not a token
   that merely appears somewhere in a balanced pair (e.g. the matched
   [LPAREN parameter_list RPAREN] suffix, which needs no hint). [sentence] is the
   space-joined known stack suffix — split into tokens as [find_matching_depth]
   does, since the raw stack lines glue several tokens together. *)
let unmatched_opener_like terminals closer sentence =
  let tokens =
    String.split_on_char ' ' sentence
    |> List.map String.trim
    |> List.filter (fun s -> s <> "")
  in
  let reversed = List.rev tokens in
  let rec scan balance = function
    | [] -> false
    | token :: rest ->
        if token = closer then scan (balance + 1) rest
        else if opener_like terminals closer token then
          if balance > 0 then scan (balance - 1) rest else true
        else scan balance rest
  in
  scan 0 reversed

let renders_as_jargon terminals s =
  String.uppercase_ascii s = s
  && (not (Hashtbl.mem terminals s))
  && special_name s = None
  && String.contains s '_'

let generate_message grammar terminals ~comments entry =
  let d = entry.Parse_messages.data in

  (* Calculate Valid Next Symbols *)
  let valid_next =
    List.fold_left
      (fun acc item ->
        let next_map =
          collect_continuations grammar StringSet.empty
            item.Parse_messages.rhs_after item.Parse_messages.lookaheads
        in
        union_status acc next_map)
      StatusMap.empty d.lr1_items
  in
  let valid_symbols = StatusMap.bindings valid_next |> List.map fst in

  let sentence =
    if d.stack_suffix <> [] then String.concat " " d.stack_suffix
    else entry.Parse_messages.sentence
  in

  let buf = Buffer.create 256 in

  (* Output: Original Sentence and Comments. The [##] comments carry state
     numbers and LR items, which churn wholesale on any grammar change; the
     [comments:false] mode omits them so the output is a stable
     sentence-to-message projection, suitable as a promoted golden file. *)
  if comments && entry.Parse_messages.original_comments <> [] then
    Printf.bprintf buf "%s: %s\n%s\n\n" entry.Parse_messages.entry_point
      entry.Parse_messages.sentence
      (String.concat "\n" entry.Parse_messages.original_comments)
  else
    Printf.bprintf buf "%s: %s\n\n" entry.Parse_messages.entry_point
      entry.Parse_messages.sentence;

  (* Heuristic: Formatting Logic *)
  let readable_name = get_readable_name terminals in

  (* Heuristic: Expected Symbols *)
  let expected_raw =
    valid_symbols
    |> List.filter (fun s -> not (involves_anonymous s)) (* Filter anonymous *)
    |> List.sort_uniq String.compare
  in
  let expected_symbols =
    (* Collapse an operator class only when it has >=2 members present in this
       state, so a *large* operator continuation reads "an operator" while a lone
       operator keeps its precise spelling (rendering a single valid operator as
       "an operator" would wrongly suggest others are legal). The class then
       counts as one symbol against the <=5 cap. *)
    let class_counts =
      List.fold_left
        (fun acc s ->
          match classify_symbol s with
          | Some c ->
              StringMap.update c
                (function None -> Some 1 | Some n -> Some (n + 1))
                acc
          | None -> acc)
        StringMap.empty expected_raw
    in
    expected_raw
    |> List.map (fun s ->
        match classify_symbol s with
        | Some c when StringMap.find c class_counts >= 2 -> c
        | _ -> readable_name s)
    |> List.sort_uniq String.compare
  in

  (* Heuristic: Unclosed Delimiters *)
  let check_unclosed closer opener_str friendly_name =
    if List.mem closer valid_symbols then
      match find_matching_depth terminals sentence closer with
      | Some depth -> Some (depth, opener_str, friendly_name)
      | None -> None
    else None
  in

  let unclosed_details =
    (* A [<N>] hint resolves N as a stack-cell index at runtime, so it is only
       sound when [find_matching_depth] scanned the *known stack suffix*. With no
       stack suffix the depth would index the raw sentence's tokens, not stack
       cells, and the runtime anchor would be wrong — so emit no hint. *)
    if d.stack_suffix = [] then None
    else
      (* Several closers can be valid in one state; hint at the *innermost* open
         construct — the one whose opener sits nearest the top of the stack
         (smallest depth) — since that is the construct the error is directly
         inside. A stable sort keeps the brace/bracket/paren tie-break order. *)
      [
        check_unclosed "RBRACE" "{" "brace";
        check_unclosed "RBRACKET" "[" "bracket";
        check_unclosed "RPAREN" "(" "parenthesis";
      ]
      |> List.filter_map Fun.id
      |> List.stable_sort (fun (d1, _, _) (d2, _, _) -> compare d1 d2)
      |> function
      | [] -> None
      | x :: _ -> Some x
  in

  (* Construct Error Message *)
  let base_message =
    if List.length expected_symbols > 0 && List.length expected_symbols <= 5
    then Printf.sprintf "Expecting %s." (format_human_list expected_symbols)
    else "Syntax error"
  in

  let message_body =
    match List.rev d.spurious_reductions with
    | [] -> base_message
    | last :: _ ->
        let raw_name = readable_name last.symbol in
        let name, verb =
          if String.length raw_name > 2 && String.sub raw_name 0 2 = "a " then
            (String.sub raw_name 2 (String.length raw_name - 2), "is")
          else if String.length raw_name > 3 && String.sub raw_name 0 3 = "an "
          then (String.sub raw_name 3 (String.length raw_name - 3), "is")
          else if String.length raw_name > 0 && String.get raw_name 0 = '\''
          then (raw_name, "is")
          else (raw_name, "are")
        in
        Printf.sprintf "Assuming that the %s %s complete, %s" name verb
          (if base_message = "Syntax error" then "syntax error."
           else String.uncapitalize_ascii base_message)
  in

  (* Append Hint if an unclosed delimiter was detected on the stack context *)
  let full_message =
    match unclosed_details with
    | Some (depth, opener, _) ->
        (* Locate the opener of the construct the error sits inside, without
           claiming it is unmatched: the same error state is reached both when
           the construct is genuinely unclosed (an EOF cut it short) and when a
           later token inside an already-closed construct is invalid, so a
           "might be unmatched" reading would be false in the latter, common
           case. A purely locational hint is true in both. *)
        message_body ^ "\n"
        ^ Printf.sprintf "<%d>This '%s' opens the enclosing construct." depth
            opener
    | None -> message_body
  in

  Printf.bprintf buf "%s\n\n" full_message;

  (* Self-lints, reported by the [-stats] mode. *)
  let n_expected = List.length expected_symbols in
  let emitted = n_expected > 0 && n_expected <= 5 in
  let missed_hints =
    List.filter
      (fun closer ->
        List.mem closer valid_symbols
        && find_matching_depth terminals sentence closer = None
        && unmatched_opener_like terminals closer
             (String.concat " " d.stack_suffix))
      [ "RBRACE"; "RBRACKET"; "RPAREN" ]
  in
  let jargon =
    if emitted then
      List.fold_left
        (fun acc s ->
          if renders_as_jargon terminals s then StringSet.add s acc else acc)
        StringSet.empty expected_raw
    else StringSet.empty
  in
  let stat =
    {
      expecting = emitted;
      assuming = d.spurious_reductions <> [];
      empty_expected = n_expected = 0;
      overflow_expected = n_expected > 5;
      hinted = unclosed_details <> None;
      missed_hints;
      jargon;
    }
  in
  (Buffer.contents buf, stat)

(* Analysis: List all possible continuations for states, indicating spurious reductions. *)
let analyze_transitions terminals entries =
  let grammar = build_grammar entries in
  let seen_states = Hashtbl.create 100 in

  Printf.printf "Transitions per state:\n";

  let process_entry entry =
    let d = entry.Parse_messages.data in
    if not (Hashtbl.mem seen_states d.state) then (
      Hashtbl.add seen_states d.state ();

      let all_next =
        List.fold_left
          (fun acc item ->
            let next_map =
              collect_continuations grammar StringSet.empty
                item.Parse_messages.rhs_after item.Parse_messages.lookaheads
            in
            union_status acc next_map)
          StatusMap.empty d.lr1_items
      in

      let symbols = StatusMap.bindings all_next in
      (match List.rev d.spurious_reductions with
      | [] -> Printf.printf "State %d:\n" d.state
      | last :: _ ->
          Printf.printf "State %d (spurious reduction: %s):\n" d.state
            last.symbol);

      let sentence =
        if d.stack_suffix <> [] then String.concat " " d.stack_suffix
        else entry.Parse_messages.sentence
      in

      List.iter
        (fun (s, status) ->
          let note =
            match status with
            | Direct -> ""
            | Lookahead -> " [lookahead]"
            | Both -> " [lookahead]"
          in

          let warning =
            match s with
            | "RBRACE" | "RBRACKET" | "RPAREN" -> (
                match find_matching_depth terminals sentence s with
                | Some depth -> Printf.sprintf " [depth: %d]" depth
                | None -> " [mismatch?]")
            | _ -> ""
          in

          Printf.printf "  %s%s%s\n" s note warning)
        symbols)
  in

  List.iter process_entry entries

(* Aggregate the per-entry self-lints into the quality summary pinned by the
   promoted [parser_messages.stats.expected] goldens: regressions (a new
   fallback state, a lost hint, a jargon token) fail `dune runtest`;
   improvements are accepted with `dune promote`. *)
let output_stats results =
  let count f = List.length (List.filter (fun (_, s) -> f s) results) in
  Printf.printf "entries: %d\n" (List.length results);
  Printf.printf "with an expected list: %d\n" (count (fun s -> s.expecting));
  Printf.printf "using the spurious-reduction template: %d\n"
    (count (fun s -> s.assuming));
  Printf.printf "generic fallback (empty expected list): %d\n"
    (count (fun s -> s.empty_expected));
  Printf.printf "generic fallback (expected list over 5): %d\n"
    (count (fun s -> s.overflow_expected));
  Printf.printf "delimiter hints: %d\n" (count (fun s -> s.hinted));
  let missed =
    List.concat_map
      (fun (entry, s) ->
        List.map (fun closer -> (closer, entry)) s.missed_hints)
      results
  in
  Printf.printf "missed delimiter hints (opener on stack, none matched): %d\n"
    (List.length missed);
  List.iter
    (fun (closer, entry) ->
      Printf.printf "  %s %s: %s\n" closer entry.Parse_messages.entry_point
        entry.Parse_messages.sentence)
    missed;
  let jargon =
    List.fold_left
      (fun acc (_, s) -> StringSet.union acc s.jargon)
      StringSet.empty results
  in
  Printf.printf "jargon-rendered tokens: %d\n" (StringSet.cardinal jargon);
  StringSet.iter (fun s -> Printf.printf "  %s\n" s) jargon

(* --- Main Entry Point --- *)

let main () =
  let input_file = ref "" in
  let generate_messages = ref false in
  let no_comments = ref false in
  let stats = ref false in
  let list_transitions = ref false in
  let terminals_file = ref "" in

  let spec =
    [
      ( "-generate-messages",
        Arg.Set generate_messages,
        "Generate error messages for states" );
      ( "-no-comments",
        Arg.Set no_comments,
        "Omit the auto-generated ## comments (state numbers, LR items) from \
         the output, keeping only the sentence and message" );
      ( "-stats",
        Arg.Set stats,
        "Print the message-quality summary (fallback/hint counts, self-lints) \
         instead of the messages" );
      ( "-list-transitions",
        Arg.Set list_transitions,
        "List all possible continuations for states" );
      ( "-terminals",
        Arg.Set_string terminals_file,
        "Path to the .mly file containing terminal definitions (required for \
         -generate-messages and -stats)" );
    ]
  in

  let usage_msg = "Usage: main.exe [options] <filename.messages>" in

  Arg.parse spec (fun f -> input_file := f) usage_msg;

  if !input_file = "" then (
    Arg.usage spec usage_msg;
    exit 1);

  if !generate_messages && !list_transitions then (
    Printf.eprintf
      "Error: -generate-messages and -list-transitions are mutually exclusive.\n";
    exit 1);

  let entries = Parse_messages.parse_file !input_file in
  Printf.eprintf "Parsed %d entries from %s\n" (List.length entries) !input_file;

  if !generate_messages || !stats then (
    if !terminals_file = "" then (
      Printf.eprintf
        "Error: -terminals is required for -generate-messages and -stats.\n";
      exit 1);
    let terminals = load_terminals !terminals_file in
    let grammar = build_grammar entries in
    if !generate_messages then Printf.eprintf "Generating messages...\n";
    let results =
      List.map
        (fun entry ->
          let text, stat =
            generate_message grammar terminals ~comments:(not !no_comments)
              entry
          in
          (entry, (text, stat)))
        entries
    in
    if !generate_messages then
      List.iter (fun (_, (text, _)) -> print_string text) results;
    if !stats then
      output_stats (List.map (fun (entry, (_, stat)) -> (entry, stat)) results))
  else if !list_transitions then
    let terminals =
      if !terminals_file = "" then Hashtbl.create 1
      else load_terminals !terminals_file
    in
    analyze_transitions terminals entries
  else if
    (* Default verification dump *)
    entries <> []
  then (
    let first = List.hd entries in
    Printf.printf "First Entry State: %d\n" first.data.state;
    Printf.printf "First Entry Info: %d items\n"
      (List.length first.data.lr1_items))

let () = main ()
